//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteDbEntities2 : DbContext
    {
        public SiteDbEntities2()
            : base("name=SiteDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal static SiteDbEntities2 GetData()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<MonitoringEmail> MonitoringEmail { get; set; }
        public virtual DbSet<MonitoringSite> MonitoringSite { get; set; }
        public virtual DbSet<MonitoringSiteEmail> MonitoringSiteEmail { get; set; }
        public virtual DbSet<MonitoringUser> MonitoringUser { get; set; }
        public IEnumerable<DataRow> Rows { get; internal set; }
    }
}
