//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitoringSiteEmail
    {
        public int MonitoringSiteEmailId { get; set; }
        public int EmailId { get; set; }
        public int MonitoringSiteId { get; set; }
    }
}
